name: QA Engineer CI/CD

on:
  push:
    branches: [ qa-engineer ]
  pull_request:
    branches: [ qa-engineer ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Scan
        run: |
          docker run -v ${{ github.workspace }}:/path zricethezav/gitleaks:latest detect --source /path --verbose
1