name: gitaction workflow  pipeline 

on:
  push:
    branches: [ qa-engineer ]

    paths:
      - ".github/workflows/qa-engineer-ci*"
      - "simplebank/backend/account-service/**"
      - "simplebank/backend/transaction-service/**"
      - "simplebank/backend/user-service/**"
      - "Dockerfile"

jobs:
  gitleaks-scan:
    name: Secuirty  Gitleak Scanning 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks (Docker)
        run: |
          echo "🔍 Running Gitleaks secret scan using Docker..."
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            zricethezav/gitleaks:latest \
            detect \
            --source=/repo \
            --report-format=json \
            --report-path=/repo/gitleaks-report.json \
            --redact \
            --verbose \
            --exit-code 1

     
      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

  checkov-terraform:
    name: Secuirty Terraform scanning 
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on Terraform
        run: |
          checkov \
            -d ./Terraform \
            --framework terraform \
            --output json \
            > checkov-terraform-report.json || true

      - name: Upload Terraform Checkov report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-terraform-report
          path: checkov-terraform-report.json

  checkov-backend-dockerfile:
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on backend  Dockerfiles
        run: |
          checkov \
            -d ./simplebank/backend/account-service/ \
            --framework dockerfile \
            --output json \
            > checkov-backend-account-service-dockerfile-report.json || true

      - name: Upload Dockerfile Checkov report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-backend-account-service-dockerfile-report
          path: checkov-backend-account-service-dockerfile-report.json

  checkov-user-service-dockerfile:
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on backend  Dockerfiles
        run: |
          checkov \
            -d ./simplebank/backend/user-service/ \
            --framework dockerfile \
            --output json \
            > checkov-backend-user-service-dockerfile-report.json || true

      - name: Upload Dockerfile Checkov report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-backend-user-service-dockerfile-report
          path: checkov-backend-user-service-dockerfile-report.json

  checkov-transaction-service-dockerfile:
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on backend  Dockerfiles
        run: |
          checkov \
            -d ./simplebank/backend/transaction-service/ \
            --framework dockerfile \
            --output json \
            > checkov-backend-transaction-service-dockerfile-report.json || true

      - name: Upload Dockerfile Checkov report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-backend-transaction-service-dockerfile-report
          path: checkov-backend-transaction-service-dockerfile-report.json


  checkov-dockerfile:
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on Dockerfiles
        run: |
          checkov \
            -d . \
            --framework dockerfile \
            --output json \
            > checkov-dockerfile-report.json || true

      - name: Upload Dockerfile Checkov report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-dockerfile-report
          path: checkov-dockerfile-report.json

  checkov-kubernetes:
    name: Security Kubernetes YAML Scanning (Multi-Directory)
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on Kubernetes Manifests
        run: |
    
          checkov -d ./k8s/account-service \
            --framework kubernetes \
            --output json \
            > checkov-k8s-account.json || true

          checkov -d ./k8s/transaction-service \
            --framework kubernetes \
            --output json \
            > checkov-k8s-transaction.json || true

    
          checkov -d ./k8s/user-service \
            --framework kubernetes \
            --output json \
            > checkov-k8s-user.json || true

      - name: Upload Kubernetes Checkov Reports
        uses: actions/upload-artifact@v4
        with:
          name: checkov-kubernetes-reports
          path: |
            checkov-k8s-account.json
            checkov-k8s-transaction.json
            checkov-k8s-user.json

  trivy-qasecurity-fs-scan:
    name: Security - Trivy FS Scan (Backend + Frontend)
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Trivy FS Scan - Account Service
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-path: "./simplebank/backend/account-service"
          severity: "HIGH,CRITICAL"
          format: "json"
          output: "trivy-account-service.json"

     
      - name: Trivy FS Scan - User Service
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-path: "./simplebank/backend/user-service"
          severity: "HIGH,CRITICAL"
          format: "json"
          output: "trivy-user-service.json"

    
      - name: Trivy FS Scan - Transaction Service
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-path: "./simplebank/backend/transaction-service"
          severity: "HIGH,CRITICAL"
          format: "json"
          output: "trivy-transaction-service.json"

      - name: Upload Trivy FS Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-reports
          path: |
            trivy-account-service.json
            trivy-user-service.json
            trivy-transaction-service.json
            

  
  trivy-qasecurity-fs-frontend-scan:
    name: Security - Trivy FS Scan (Backend + Frontend)
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  
          
      - name: Trivy FS Scan - Frontend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-path: "./src"
          severity: "HIGH,CRITICAL"
          format: "json"
          output: "trivy-frontend.json"

      - name: Upload Trivy FS Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-reports
          path: |
            trivy-frontend.json

